spring:
  application:
    name: ApiMonitoreo
    security:
      jwt:
        secret-key: f5f089c5324dcbf107086b08bb7f874bcbf683745484b6684df6d7fc9e591fea
        expiration: 86400000
  datasource:
    url: jdbc:postgresql://localhost:5431/monitoreodb
    username: luisvill
    password: luisvill
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  email:
    sender: bovintrack@gmail.com
    password: rckezgqhalkaukwa

logging:
  level:
    org.hibernate: info


server:
  port: 8090
