CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE bovinos
    ALTER COLUMN codigo SET DEFAULT uuid_generate_v4();

ALTER TABLE fincas
    ALTER COLUMN id_finca SET DEFAULT uuid_generate_v4();

ALTER TABLE historial_ubicaciones
    ALTER COLUMN id_historial SET DEFAULT uuid_generate_v4();

ALTER TABLE potreros
    ALTER COLUMN id_potrero SET DEFAULT uuid_generate_v4();

ALTER TABLE roles
    ALTER COLUMN id_rol DROP DEFAULT,
    ALTER COLUMN id_rol SET DATA TYPE INTEGER,
    ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE sensores
    ALTER COLUMN codigo SET DEFAULT uuid_generate_v4();

ALTER TABLE usuarios
    ALTER COLUMN id_usuario SET DEFAULT uuid_generate_v4();
